<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_testtest.test</name>
   <tag></tag>
   <elementGuidId>6fb04c1c-9229-41d0-9e01-b79a6f6a85d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.px-6.py-2.text-white.bg-red-secondary.border.border-red-secondary.border-opacity-50.rounded-full.flex.justify-center.mb-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[5]/div[2]/div/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9dc49cfd-abc1-471e-bde8-dcecab93137f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-6 py-2 text-white bg-red-secondary border border-red-secondary border-opacity-50 rounded-full flex justify-center mb-4</value>
      <webElementGuid>74547425-5e9e-44c6-b039-d48a1f0301b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> te**st@test.test</value>
      <webElementGuid>242efec4-4b84-4388-b68c-d20dbf5f48b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;bg-blue-1 flex flex-col min-h-screen text-white font-montserrat&quot;]/div[@class=&quot;vm--container&quot;]/div[@class=&quot;vm--modal modal-classes mx-auto&quot;]/div[@class=&quot;text-white layout-verify-wrapper&quot;]/div[@class=&quot;flex w-full flex-col items-center&quot;]/div[@class=&quot;px-6 py-2 text-white bg-red-secondary border border-red-secondary border-opacity-50 rounded-full flex justify-center mb-4&quot;]</value>
      <webElementGuid>3c283c6f-902f-4443-8e8e-8ee0818f96f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[5]/div[2]/div/div[2]/div[2]</value>
      <webElementGuid>8f9f4db0-a10e-41ad-93cd-33b1689cbd8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email Kamu belum terverifikasi'])[1]/following::div[1]</value>
      <webElementGuid>e6e94e63-e073-4fdf-9c3b-4b9d0d3d2b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verifikasi'])[1]/following::div[3]</value>
      <webElementGuid>eb7071e8-9070-450b-90bf-7590e6c5c6bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lakukan verifikasi email untuk bisa masuk ke akun bioskop online'])[1]/preceding::div[1]</value>
      <webElementGuid>e90a0c35-3ceb-496b-acbf-7f7c8477af73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div[2]/div[2]</value>
      <webElementGuid>d7777600-ecbe-414e-8d6d-8dc0a56b2c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' te**st@test.test' or . = ' te**st@test.test')]</value>
      <webElementGuid>fe2b3cee-cfa9-49dc-b064-89db98ee0735</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
