<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Keluar</name>
   <tag></tag>
   <elementGuidId>ce08d648-e2a3-4cab-847c-3c98b4b3ba05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.text-sm.font-bold.text-white.mt-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/div/div/div[4]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0ad23bc8-8223-49b5-b773-68712efb69e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-sm font-bold text-white mt-4</value>
      <webElementGuid>1f71f9c5-c654-4250-a77c-188d4127e80b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
        Keluar
      </value>
      <webElementGuid>331450e1-93ed-4150-917a-e7047bc4fc5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;bg-blue-1 flex flex-col min-h-screen text-white font-montserrat&quot;]/div[@class=&quot;flex-1 flex flex-col pb-24&quot;]/div[@class=&quot;flex desktop:items-center justify-center flex-1 py-8&quot;]/div[@class=&quot;text-white layout-menu-wrapper pb-9&quot;]/div[@class=&quot;container mx-auto flex flex-col&quot;]/button[@class=&quot;text-sm font-bold text-white mt-4&quot;]</value>
      <webElementGuid>078cbd3e-2d7d-4f1d-8d69-4663fb0663af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/div/div/div[4]/button</value>
      <webElementGuid>ff8403ce-6540-45e6-9f89-4b56ac109593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang Kami'])[1]/following::button[1]</value>
      <webElementGuid>71306fbb-c89c-4b58-8ad8-1879f9b01501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ketentuan Layanan'])[1]/following::button[2]</value>
      <webElementGuid>cb68a35d-6206-43c7-b927-f8c00d5851e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pusat Bantuan'])[3]/preceding::button[1]</value>
      <webElementGuid>f1857231-804a-4b9f-aa84-b32da579d65e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang Bioskop Online'])[1]/preceding::button[1]</value>
      <webElementGuid>84794359-d0fa-4d55-8557-7310c283e326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[4]/button</value>
      <webElementGuid>07d27608-2ff7-4c5d-ab66-4f0e740d4b03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
        Keluar
      ' or . = '
        Keluar
      ')]</value>
      <webElementGuid>6e99fba0-117a-44ac-8862-0cc5184183b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
