<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>circle</name>
   <tag></tag>
   <elementGuidId>6f1cff4e-575b-433b-a4cc-650281f2eee6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>051461bc-8f78-48f7-b236-0adff16576b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>f48125db-da82-4c4e-bcaf-8ae87379cbeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>7849e0dd-aa63-4179-bee6-7c7103029e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>774610f1-3aa9-429e-b8ff-96d22a9b82de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;bg-blue-1 flex flex-col min-h-screen text-white font-montserrat&quot;]/div[@class=&quot;vm--container&quot;]/div[@class=&quot;vm--modal modal-classes mx-auto full-height&quot;]/div[@class=&quot;text-white layout-voucher-wrapper&quot;]/div[@class=&quot;p-4 mobile:p-2 flex-1 flex flex-col overflow-auto&quot;]/div[@class=&quot;flex justify-between items-center mb-4&quot;]/svg[@class=&quot;cursor-pointer mobile:hidden&quot;]/circle[1]</value>
      <webElementGuid>f5ca556f-139b-4868-aa09-d2fbf149e632</webElementGuid>
   </webElementProperties>
</WebElementEntity>
