<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Selengkapnya</name>
   <tag></tag>
   <elementGuidId>f58bf377-3c30-4c9d-b136-0e5f07d74d4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.text-xxs.text-blue-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>921318ce-c22d-4111-a927-b8cea364fc1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-xxs text-blue-4</value>
      <webElementGuid>e2bb614d-ee97-44c6-9bf1-ac3689591771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selengkapnya</value>
      <webElementGuid>7c62a4c7-587d-4ff7-a7a3-7ea4a2531cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;bg-blue-1 flex flex-col min-h-screen text-white font-montserrat&quot;]/div[@class=&quot;flex-1 flex flex-col pb-24&quot;]/div[@class=&quot;flex-1 flex flex-col&quot;]/div[1]/div[@class=&quot;container mx-auto py-8 mobile:py-16&quot;]/div[@class=&quot;mb-14 mobile:mb-10&quot;]/a[@class=&quot;flex justify-between items-center mb-5&quot;]/div[@class=&quot;text-xxs text-blue-4&quot;]</value>
      <webElementGuid>fa592cb1-b9b5-4353-ac39-90deabb9bf96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/div/div/div[2]/div/a/div[2]</value>
      <webElementGuid>de408bc5-524d-487d-a684-2144d3dc3957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paling Dicari'])[1]/following::div[1]</value>
      <webElementGuid>60c87fe0-3e6c-44cb-be4b-be1b610b789d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat'])[18]/following::div[6]</value>
      <webElementGuid>7c1569f0-81d1-4c13-aaa8-3860e0d6ab93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Promo Hari Ini'])[1]/preceding::div[36]</value>
      <webElementGuid>5d5aab69-cf33-4a81-badb-0d4930353676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selengkapnya'])[2]/preceding::div[37]</value>
      <webElementGuid>8ce26a89-da56-4074-8356-6306e2c3a075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Selengkapnya']/parent::*</value>
      <webElementGuid>7096acc4-8d69-429f-ad2a-cc5597f6a574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]</value>
      <webElementGuid>cf549a07-af8f-4085-9729-e0b9ee0e3643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Selengkapnya' or . = 'Selengkapnya')]</value>
      <webElementGuid>d475f32c-3de5-4727-8ad8-974523b4db47</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
