<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign Up</name>
   <tag></tag>
   <elementGuidId>1288e843-7557-4d72-8701-3c5a37091272</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#u_0_s_XK</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='u_0_s_XK']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7f11dbdb-a6d6-4031-9260-9eacf3edfb3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1e9ea368-3945-4738-b7c3-9e75832e7f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_6j mvm _6wk _6wl _58mi _3ma _6o _6v</value>
      <webElementGuid>cae6a507-97f2-4d1c-b69c-e14a60c7e6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>websubmit</value>
      <webElementGuid>83707cfb-e83e-4f04-8a29-7e286adade95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_0_s_XK</value>
      <webElementGuid>e177398e-7ede-426a-b16a-7c99579d592f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign Up</value>
      <webElementGuid>8dc722f1-b9ed-49d1-a34c-e37cddb07c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_s_XK&quot;)</value>
      <webElementGuid>e5ffbdae-e786-48bb-8d7f-eac3dac9188b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='u_0_s_XK']</value>
      <webElementGuid>19289383-3852-4637-9f7d-5e00e4bf2415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='reg_form_box']/div[11]/button</value>
      <webElementGuid>92c32663-8409-41e6-bec9-2c2a2d576180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookies Policy'])[1]/following::button[1]</value>
      <webElementGuid>0c6cc443-1c66-4dbf-9827-6cff611e7531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/following::button[1]</value>
      <webElementGuid>ac114a53-0281-4675-9b4f-ac54cd7fc101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Already have an account?'])[1]/preceding::button[1]</value>
      <webElementGuid>1fcb9653-b66d-4388-a18f-a58465f694ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Security check'])[1]/preceding::button[1]</value>
      <webElementGuid>c5906a2d-80eb-4442-a75c-066f884f4bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign Up']/parent::*</value>
      <webElementGuid>5e36b295-7a1b-4ed0-b0b7-5620eac0be8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>d0321e62-13bf-4f83-a8c3-9f622be31267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'websubmit' and @id = 'u_0_s_XK' and (text() = 'Sign Up' or . = 'Sign Up')]</value>
      <webElementGuid>71e15c75-1221-4829-861d-71f8417313a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
