<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__TquXA</name>
   <tag></tag>
   <elementGuidId>cf238dad-320f-49a0-b74c-6d3ab1dd4628</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.TquXA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='lang-chooser']/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>528f48be-6654-49d2-945c-39062dbf3f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TquXA</value>
      <webElementGuid>4a593401-8f07-473f-b60b-5c893ce4498b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lang-chooser&quot;)/div[1]/div[@class=&quot;CeEBt Ce1Y1c eU809d&quot;]/div[@class=&quot;TquXA&quot;]</value>
      <webElementGuid>9748da42-c565-4e20-b6cd-1555fd3a5987</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lang-chooser']/div/div[2]/div</value>
      <webElementGuid>5235a1a2-cc4c-4be0-a1ca-8af201687eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/div/div/div[2]/div</value>
      <webElementGuid>8e065465-84dc-4f5a-8275-61665e532774</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
